PADDLE_SPEED_PER_SECOND_MAX = 0.6
PADDLE_SPEED_PER_SECOND_TOLERANCE = 1.01
PADDLE_RATIO = 0.3
PADDLE_POSITION_MIN: float = PADDLE_RATIO / 2
PADDLE_POSITION_MAX: float = 1 - PADDLE_POSITION_MIN

MAP_SIZE_X = 500
MAP_SIZE_Y = 500
MAP_CENTER_X = MAP_SIZE_X / 2
MAP_CENTER_Y = MAP_SIZE_Y / 2

WALL_RATIO = 1

BALL_SPEED_MAX = 550
BALL_SPEED_INC = 50
BALL_SPEED_START = 170
BALL_SIZE = 4
BALL_SPAWN_POS_X = MAP_SIZE_X / 2
BALL_SPAWN_POS_Y = MAP_SIZE_Y / 2

SERVER_TPS = 20

STROKE_THICKNESS = 10

GAME_MAX_SCORE = 3